from ubuntu:18.04
MAINTAINER Tuhin Sharma "tuhinsharma121@gmail.com"

# --------------------------------------------------------------------------------------------------
# install ubuntu essentials
# --------------------------------------------------------------------------------------------------

RUN apt-get update --fix-missing && \
    apt-get -y install build-essential && \
    apt-get install -y apt-utils && \
    apt-get -y install zlib1g-dev && \
    apt-get install -y libssl-dev && \
    apt-get install -y libbz2-dev && \
    apt-get install -y liblzma-dev && \
    apt-get -y install wget

# --------------------------------------------------------------------------------------------------
# install python 3.6.8
# --------------------------------------------------------------------------------------------------

RUN wget https://www.python.org/ftp/python/3.6.8/Python-3.6.8.tgz && \
    tar -xzf Python-3.6.8.tgz && \
    cd Python-3.6.8 && \
    ./configure && \
    make && \
    make install

## --------------------------------------------------------------------------------------------------
## install python packages
## --------------------------------------------------------------------------------------------------

COPY ./requirements.txt /
RUN pip3 install -r /requirements.txt

# --------------------------------------------------------------------------------------------------
# copy src code and scripts into root dir /
# --------------------------------------------------------------------------------------------------

COPY ./application_platform /application_platform
COPY ./config.py.template /config.py

# --------------------------------------------------------------------------------------------------
# add entrypoint for the container
# --------------------------------------------------------------------------------------------------
ADD ./deployment_config/scripts/entrypoint.sh /bin/entrypoint.sh
RUN chmod +x /bin/entrypoint.sh
ENTRYPOINT ["/bin/entrypoint.sh"]